### ISSUE TITLE
Bug in param_types checking?

### ISSUE THREAD

**Issue by vchong** [jbech-linaro/template_ta#1]
Won't https://github.com/jbech-linaro/template_ta/blob/master/ta/template_ta.c#L63-L68 cause an error because https://github.com/jbech-linaro/template_ta/blob/master/host/main.c#L75-L78?

**Comment by jockebech** [comment]
Yes, that needs to be updated.

**Comment by vchong** [comment]
+@jenswi-linaro

Same issue here:
https://github.com/jbech-linaro/comcast_cryptoapi_ta_example/blob/master/ta/comcast_crypto_gp_ta.c#L78-L83 and https://github.com/jbech-linaro/comcast_cryptoapi_ta_example/blob/master/host/comcast_crypto_gp_client.c#L95-L98

and here:
https://github.com/jenswi-linaro/lcu14_optee_hello_world/blob/master/ta/hello_world_ta.c#L60-L65 and https://github.com/jenswi-linaro/lcu14_optee_hello_world/blob/master/host/hello_world.c#L70-L71

Do you guys maybe mean "==" to make sure at least one param gets passed to the TA? Or if all four params can be none, then maybe this check is not required? All the xtest TAs and static TAs don't have this check.

**Comment by jenswikl** [comment]
To me it looks that in each of these cases the client has initialized param_types for an invoke command while the lines you're pointing at in the TAs are for the open session.

**Comment by vchong** [comment]
So at open session they are all supposed to be none? An "IS" an error if they're not?

**Comment by jenswikl** [comment]
In these cases, yes.

**Comment by vchong** [comment]
Ok. Thanks for explaining! Closing.
